apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "new-api.fullname" . }}
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.database.type "sqlite" }}
  SQLITE_PATH: {{ .Values.database.sqlite.path | quote }}
  {{- end }}
